INSERT INTO construction.permission (id,version,action_name,code_name,description,entity_name) VALUES
	 (1,0,'ALL','ALL_ALL','ALL PERMISSIONS','ALL'),
	 (2,0,'READ','READ_ALL','READ ALL ENTITY','ALL'),
	 (3,0,'READ','READ_USER','READ ALL USER','USER'),
	 (4,0,'CREATE','CREATE_USER','CREATE USER','USER'),
	 (5,0,'UPDATE','UPDATE_USER','UPDATE ALL USER','USER'),
	 (6,0,'DELETE','DELETE_USER','DELETE ALL USER','USER'),
	 (12,0,'READ','READ_PROJECT','READ ALL PROJECT','PROJECT'),
	 (13,0,'FULL','FULL_PROJECT','FULL ACCESS ON PROJECT','PROJECT'),
	 (14,0,'CREATE','CREATE_PROJECT','CREATE PROJECT','PROJECT'),
	 (16,0,'UPDATE','UPDATE_PROJECT','UPDATE ALL PROJECT','PROJECT');
INSERT INTO construction.permission (id,version,action_name,code_name,description,entity_name) VALUES
	 (18,0,'DELETE','DELETE_PROJECT','DELETE ALL PROJECT','PROJECT'),
	 (20,0,'ASSIGN','ASSIGN_PROJECT','ASSIGN ALL PROJECT','PROJECT'),
	 (21,0,'ASSIGN_ASSIGNED','ASSIGN_ASSIGNED_PROJECT','ASSIGN ASSIGNED PROJECT','PROJECT'),
	 (22,0,'VERIFY','VERIFY_PROJECT','VERIFY ALL PROJECT','PROJECT'),
	 (24,0,'APPROVE','APPROVE_PROJECT','APPROVE ALL PROJECT','PROJECT'),
	 (28,0,'READ','READ_TASK','READ ALL TASK','TASK'),
	 (29,0,'FULL','FULL_TASK','FULL ACCESS ON TASK','TASK'),
	 (30,0,'CREATE','CREATE_TASK','CREATE TASK','TASK'),
	 (32,0,'UPDATE','UPDATE_TASK','UPDATE ALL TASK','TASK'),
	 (34,0,'DELETE','DELETE_TASK','DELETE ALL TASK','TASK');
INSERT INTO construction.permission (id,version,action_name,code_name,description,entity_name) VALUES
	 (36,0,'ASSIGN','ASSIGN_TASK','ASSIGN ALL TASK','TASK'),
	 (37,0,'ASSIGN_ASSIGNED','ASSIGN_ASSIGNED_TASK','ASSIGN ASSIGNED TASK','TASK'),
	 (38,0,'VERIFY','VERIFY_TASK','VERIFY ALL TASK','TASK'),
	 (40,0,'APPROVE','APPROVE_TASK','APPROVE ALL TASK','TASK'),
	 (43,0,'FULL','FULL_HOUSE','FULL ACCESS ON HOUSE','HOUSE'),
	 (44,0,'READ','READ_HOUSE','READ ALL HOUSE','HOUSE'),
	 (45,0,'ASSIGN','ASSIGN_HOUSE','ASSIGN ALL HOUSE','HOUSE'),
	 (46,0,'CREATE','CREATE_HOUSE','CREATE HOUSE','HOUSE'),
	 (47,0,'ASSIGN_ASSIGNED','ASSIGN_ASSIGNED_HOUSE','ASSIGN ASSIGNED HOUSE','HOUSE'),
	 (48,0,'UPDATE','UPDATE_HOUSE','UPDATE ALL HOUSE','HOUSE');
INSERT INTO construction.permission (id,version,action_name,code_name,description,entity_name) VALUES
	 (50,0,'DELETE','DELETE_HOUSE','DELETE ALL HOUSE','HOUSE'),
	 (54,0,'VERIFY','VERIFY_HOUSE','VERIFY ALL HOUSE','HOUSE'),
	 (56,0,'APPROVE','APPROVE_HOUSE','APPROVE ALL HOUSE','HOUSE'),
	 (59,0,'FULL','FULL_STREET','FULL ACCESS ON STREET','STREET'),
	 (60,0,'READ','READ_STREET','READ ALL STREET','STREET'),
	 (61,0,'ASSIGN_ASSIGNED','ASSIGN_ASSIGNED_STREET','ASSIGN ASSIGNED STREET','STREET'),
	 (62,0,'CREATE','CREATE_STREET','CREATE STREET','STREET'),
	 (63,0,'ASSIGN','ASSIGN_STREET','ASSIGN ALL STREET','STREET'),
	 (64,0,'UPDATE','UPDATE_STREET','UPDATE ALL STREET','STREET'),
	 (66,0,'DELETE','DELETE_STREET','DELETE ALL STREET','STREET');
INSERT INTO construction.permission (id,version,action_name,code_name,description,entity_name) VALUES
	 (70,0,'VERIFY','VERIFY_STREET','VERIFY ALL STREET','STREET'),
	 (72,0,'APPROVE','APPROVE_STREET','APPROVE ALL STREET','STREET'),
	 (76,0,'READ','READ_BOQ','READ ALL BOQ','BOQ'),
	 (78,0,'CREATE','CREATE_BOQ','CREATE BOQ','BOQ'),
	 (80,0,'UPDATE','UPDATE_BOQ','UPDATE ALL BOQ','BOQ'),
	 (82,0,'DELETE','DELETE_BOQ','DELETE ALL BOQ','BOQ'),
	 (83,0,'SUBMIT','SUBMIT_PAYMENT','SUBMIT ALL PAYMENT','PAYMENT'),
	 (84,0,'VERIFY','VERIFY_PAYMENT','VERIFY ALL PAYMENT','PAYMENT'),
	 (85,0,'CONFIRM','CONFIRM_PAYMENT','CONFIRM ALL PAYMENT','PAYMENT'),
	 (86,0,'REVIEW','REVIEW_PAYMENT','REVIEW ALL PAYMENT','PAYMENT');
INSERT INTO construction.permission (id,version,action_name,code_name,description,entity_name) VALUES
	 (87,0,'APPROVE','APPROVE_PAYMENT','APPROVE ALL PAYMENT','PAYMENT'),
	 (88,0,'CASH_OUT','CASH_OUT_PAYMENT','CASH OUT ALL PAYMENT','PAYMENT'),
	 (92,0,'READ','READ_PAYMENT','READ ALL PAYMENT','PAYMENT'),
	 (94,0,'CREATE','CREATE_PAYMENT','CREATE PAYMENT','PAYMENT'),
	 (96,0,'UPDATE','UPDATE_PAYMENT','UPDATE ALL PAYMENT','PAYMENT'),
	 (98,0,'DELETE','DELETE_PAYMENT','DELETE ALL PAYMENT','PAYMENT'),
	 (103,0,'READ','READ_SUB_CONSTRUCTOR','READ SUB-CONSTRUCTOR','SUB_CONSTRUCTOR'),
	 (105,0,'CREATE','CREATE_SUB_CONSTRUCTOR','CREATE SUB CONSTRUCTOR','SUB_CONSTRUCTOR'),
	 (106,0,'UPDATE','UPDATE_SUB_CONSTRUCTOR','UPDATE ALL SUB CONSTRUCTOR','SUB_CONSTRUCTOR'),
	 (107,0,'DELETE','DELETE_SUB_CONSTRUCTOR','DELETE ALL SUB CONSTRUCTOR','SUB_CONSTRUCTOR');
INSERT INTO construction.permission (id,version,action_name,code_name,description,entity_name) VALUES
	 (108,0,'VERIFY','VERIFY_SUB_CONSTRUCTOR','VERIFY ALL SUB CONSTRUCTOR','SUB_CONSTRUCTOR'),
	 (109,0,'APPROVE','APPROVE_SUB_CONSTRUCTOR','APPROVE ALL SUB CONSTRUCTOR','SUB_CONSTRUCTOR'),
	 (110,0,'CREATE','CREATE_TASK_TEMPLATE','CREATE TASK TEMPLATE','TASK_TEMPLATE'),
	 (111,0,'UPDATE','UPDATE_TASK_TEMPLATE','UPDATE ALL TASK TEMPLATE','TASK_TEMPLATE'),
	 (112,0,'DELETE','DELETE_TASK_TEMPLATE','DELETE ALL TASK TEMPLATE','TASK_TEMPLATE'),
	 (113,0,'VERIFY','VERIFY_TASK_TEMPLATE','VERIFY ALL TASK TEMPLATE','TASK_TEMPLATE'),
	 (114,0,'APPROVE','APPROVE_TASK_TEMPLATE','APPROVE ALL TASK TEMPLATE','TASK_TEMPLATE'),
	 (115,0,'READ','READ_TASK_TEMPLATE','READ TASK TEMPLATE','TASK_TEMPLATE'),
	 (116,0,'CREATE','CREATE_CONTRACT',NULL,'CONTRACT'),
	 (117,0,'UPDATE','UPDATE_CONTRACT',NULL,'CONTRACT');
INSERT INTO construction.permission (id,version,action_name,code_name,description,entity_name) VALUES
	 (118,0,'READ','READ_CONTRACT',NULL,'CONTRACT'),
	 (119,0,'DELETE','DELETE_CONTRACT',NULL,'CONTRACT'),
	 (120,0,'FULL','FULL_CONTRACT',NULL,'CONTRACT'),
	 (121,0,'VERIFY','VERIFY_CONTRACT',NULL,'CONTRACT'),
	 (122,0,'APPROVE','APPROVE_CONTRACT',NULL,'CONTRACT');